name: macOS (x86_64)

on:
  push:
    branches:
      - test

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        arch: [x86_64]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-${{ matrix.arch }}-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: '.xmake-cache'

      - name: Tests
        if: ${{ github.repository }} == "xmake-io/xmake-repo"
        run: |
          echo "xxxxx"
          echo ${{ github.repository }}
